version: '2'
services:
  mongodb:
    image: "mongo"
    ports:
     - "27017:27017"
  backend:
    build: ./back/
    image: nomaneoulali/backexpress
    ports:
      - "6200:6200"
    volumes:
      - ./back:/usr/src/app
    depends_on:
      - mongodb
  frontend:
    build: ./front/
    image: nomaneoulali/frontreact
    ports:
      - "3000:3000"
    volumes:
      - ./front:/usr/src/app
    depends_on:
      - backend